inputs:
    # branch:
    #   type: string
    #   required: true
    
    output:
      type: string
      require: true

runs:
  using: 'composite'
  steps:  
  # - uses: actions/checkout@v3
  #   with:
  #     ref: ${{ inputs.branch }}

  - name: Use Node.js ${{ env.node_version }}
    uses: actions/setup-node@v3
    with:
      node-version: ${{ env.node_version }}
      cache: 'yarn'

  - name: Install
    shell: bash
    run: yarn install --frozen-lockfile
    
  - name: Bundle
    shell: bash
    run: yarn bundle

  - name: Transpile helper files
    shell: bash
    run: yarn transpile-workflow-files

  - name: Create metadata file
    shell: bash
    run: yarn stats -- --out=${{ inputs.output }} --dir=dist --extensions=".js,.html,.css"

  