export const VENDORS_FORM_DRAFT_STORAGE_KEY = 'vendors-form-draft';
export const VENDORS_FORM_BUSINESS_DESCRIPTION_MAX_LENGTH = 2200;
export const VENDORS_FORM_MAX_PREFERRED_STANDS = 3;
export const VENDORS_FORM_HIGH_INTEREST_MIN_REQUESTS = 3;
export const VENDORS_FORM_LOGO_MAX_BYTES = 8 * 1024 * 1024;
export const VENDORS_FORM_LOGO_MAX_DIMENSION = 1024;
