import type { VendorApplication } from '../vendors-form/vendorsFormSubmission';

export const VENDORS_APPLICATIONS_MOCK: VendorApplication[] = [
  {
    allocatedStandId: null,
    allocationIteration: null,
    allocationState: 'none',
    id: 'mock-application-1',
    status: 'new',
    submittedAt: '2026-05-11T08:15:00.000Z',
    storeName: 'Włóczki z Krakowa',
    attendedBefore: true,
    mainCategory: 'yarns',
    mainCategoryOther: '',
    preferredStands: ['P2', 'P3', 'P1'],
    interestedIfUnavailable: true,
    phoneNumber: '+48 501 201 301',
    email: 'kontakt@wloczkizkrakowa.pl',
    invoiceDetails: 'Włóczki z Krakowa Sp. z o.o.\nul. Szewska 12\n31-009 Kraków\nNIP: 6761112233',
    logoFileName: 'wloczki-z-krakowa.png',
    logoDataUrl: null,
    logoMimeType: null,
    businessDescription: 'Farbowane ręcznie włóczki inspirowane kolorami Krakowa i Małopolski.',
    acceptedStatute: true
  },
  {
    allocatedStandId: null,
    allocationIteration: null,
    allocationState: 'none',
    id: 'mock-application-2',
    status: 'considered',
    submittedAt: '2026-05-11T09:00:00.000Z',
    storeName: 'Splot i Ścieg',
    attendedBefore: false,
    mainCategory: 'accessories',
    mainCategoryOther: '',
    preferredStands: ['P2', 'M4', 'S6'],
    interestedIfUnavailable: true,
    phoneNumber: '+48 502 202 302',
    email: 'hej@splotiscieg.pl',
    invoiceDetails: 'Splot i Ścieg\nul. Długa 5\n30-001 Kraków\nNIP: 9452223344',
    logoFileName: 'splot-i-scieg.webp',
    logoDataUrl: null,
    logoMimeType: null,
    businessDescription: 'Akcesoria do drutów i szydełka, organizery, markery i etui szyte lokalnie.',
    acceptedStatute: true
  },
  {
    allocatedStandId: null,
    allocationIteration: null,
    allocationState: 'none',
    id: 'mock-application-3',
    status: 'accepted',
    submittedAt: '2026-05-11T09:30:00.000Z',
    storeName: 'Ceramiczna Owca',
    attendedBefore: true,
    mainCategory: 'ceramics',
    mainCategoryOther: '',
    preferredStands: ['P3', 'S8', 'M2'],
    interestedIfUnavailable: false,
    phoneNumber: '+48 503 203 303',
    email: 'kontakt@ceramicznaowca.pl',
    invoiceDetails: 'Ceramiczna Owca\nul. Lea 17\n30-048 Kraków\nNIP: 6773334455',
    logoFileName: 'ceramiczna-owca.png',
    logoDataUrl: null,
    logoMimeType: null,
    businessDescription: 'Ceramika użytkowa dla dziewiarek: miski projektowe, kubki i podstawki pod schematy.',
    acceptedStatute: true
  },
  {
    allocatedStandId: null,
    allocationIteration: null,
    allocationState: 'none',
    id: 'mock-application-4',
    status: 'new',
    submittedAt: '2026-05-11T10:10:00.000Z',
    storeName: 'Płomień i Knot',
    attendedBefore: false,
    mainCategory: 'candles',
    mainCategoryOther: '',
    preferredStands: ['P2', 'P1', 'M3'],
    interestedIfUnavailable: true,
    phoneNumber: '+48 504 204 304',
    email: 'biuro@plomieniknot.pl',
    invoiceDetails: 'Płomień i Knot\nos. Zgody 3/12\n31-949 Kraków\nNIP: 6784445566',
    logoFileName: 'plomien-i-knot.avif',
    logoDataUrl: null,
    logoMimeType: null,
    businessDescription: 'Świece sojowe i zapachy tworzone z myślą o spokojnych wieczorach z robótką.',
    acceptedStatute: true
  },
  {
    allocatedStandId: null,
    allocationIteration: null,
    allocationState: 'none',
    id: 'mock-application-5',
    status: 'reserve',
    submittedAt: '2026-05-11T11:05:00.000Z',
    storeName: 'Naturalnie Plecione',
    attendedBefore: true,
    mainCategory: 'other',
    mainCategoryOther: 'Makramy i dekoracje tekstylne',
    preferredStands: ['S3', 'S4', 'P3'],
    interestedIfUnavailable: true,
    phoneNumber: '+48 505 205 305',
    email: 'hello@naturalnieplecione.pl',
    invoiceDetails: 'Naturalnie Plecione\nul. Starowiślna 20\n31-032 Kraków\nNIP: 6795556677',
    logoFileName: 'naturalnie-plecione.png',
    logoDataUrl: null,
    logoMimeType: null,
    businessDescription: 'Makramowe dekoracje i tekstylia do wnętrz wykonywane w krótkich, autorskich seriach.',
    acceptedStatute: true
  },
  {
    allocatedStandId: null,
    allocationIteration: null,
    allocationState: 'none',
    id: 'mock-application-6',
    status: 'considered',
    submittedAt: '2026-05-11T11:40:00.000Z',
    storeName: 'Mini Motek',
    attendedBefore: false,
    mainCategory: 'yarns',
    mainCategoryOther: '',
    preferredStands: ['S6', 'P1', 'P3'],
    interestedIfUnavailable: true,
    phoneNumber: '+48 506 206 306',
    email: 'kontakt@minimotek.pl',
    invoiceDetails: 'Mini Motek\nul. Karmelicka 9\n31-133 Kraków\nNIP: 9456667788',
    logoFileName: 'mini-motek.webp',
    logoDataUrl: null,
    logoMimeType: null,
    businessDescription: 'Małe serie włóczek, zestawy mini motków i kolory przygotowane pod żakardy.',
    acceptedStatute: true
  }
];
