# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Pull Request

env:
  node_version: 18
  artifact_retention_days: 3

on: pull_request

jobs:
  Install:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node_version }}
        cache: 'yarn'

    - name: Install dependencies
      id: install
      run: yarn install --frozen-dependencies
      
    - name: Typecheck
      id: typecheck
      if: always()
      run: yarn typecheck
      
    - name: Lint
      id: lint
      if: always()
      run: yarn lint

    - name: Bundle
      id: bundle
      if: always()
      run: yarn bundle

    - uses: actions/checkout@v3

    - uses: ./.github/actions/generate-metadata
      with: 
        # branch: ${{ github.ref_name }}
        output: branch-metadata

    - uses: actions/checkout@v3
      with:
        ref: master

    - uses: ./.github/actions/generate-metadata
      with: 
        # branch: master
        output: master-metadata

