# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Pull Request

on: 
  push:
    branches-ignore:
      - master

  pull_request:
    types: [opened, reopened]

jobs:
  install:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        
    - name: Install dependencies
      run: yarn install --frozen-dependencies
      
    - name: Typecheck
      run: yarn tsc
      
    - name: Lint
      run: yarn lint

    - name: Build
      run: yarn build
