# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Pull Request

env:
  node_version: 18
  artifact_retention_days: 3

on: pull_request

jobs:
  Install:
    runs-on: ubuntu-latest

    outputs:
      typecheckOutcome: ${{ steps.typecheck.outcome }}
      lintOutcome:      ${{ steps.lint.outcome }}
      bundleOutcome:    ${{ steps.bundle.outcome }}

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ env.node_version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node_version }}
        cache: 'yarn'
        
    - name: Install dependencies
      id: install
      run: yarn install --frozen-dependencies
      
    - name: Typecheck
      id: typecheck
      continue-on-error: true
      run: yarn typecheck
      
    - name: Lint
      id: lint
      continue-on-error: true
      run: yarn lint

    - name: Bundle
      id: bundle
      continue-on-error: true
      run: yarn bundle
